import type { Faction, FactionId, UnitStats, BuildingStats, Ability } from './types'

// Factions with unique characteristics
export const FACTIONS: Record<string, Faction> = {
  terran: {
    id: 'terran',
    name: 'Terran Dominion',
    description: 'Adaptable human faction with versatile infantry and powerful siege weapons. Buildings can be repaired and lifted for repositioning.',
    color: '#FF9500',
    darkColor: '#AA6600',
    lightColor: '#FFCC66',
    workerUnit: 'scv',
    baseBuilding: 'commandcenter',
    supplyBuilding: 'supplydepot',
    gasBuilding: 'refinery',
    buildStyle: 'construct',
    strengths: ['Defensive play', 'Siege warfare', 'Flexibility'],
    playstyle: 'Balanced and versatile with strong defensive options',
  },
  protoss: {
    id: 'protoss',
    name: 'Protoss Empire',
    description: 'Ancient psionic warriors with powerful shields and warp technology. Units are expensive but individually powerful.',
    color: '#00AAFF',
    darkColor: '#006699',
    lightColor: '#66CCFF',
    workerUnit: 'probe',
    baseBuilding: 'nexus',
    supplyBuilding: 'pylon',
    gasBuilding: 'assimilator',
    buildStyle: 'warp',
    strengths: ['High-tech units', 'Shield regeneration', 'Warp technology'],
    playstyle: 'Quality over quantity with powerful individual units',
  },
  zerg: {
    id: 'zerg',
    name: 'Zerg Swarm',
    description: 'Insectoid alien swarm that overwhelms enemies with numbers. Units morph from workers and all buildings must be on creep.',
    color: '#AA44FF',
    darkColor: '#6622AA',
    lightColor: '#CC88FF',
    workerUnit: 'drone',
    baseBuilding: 'hatchery',
    supplyBuilding: 'overlord',
    gasBuilding: 'extractor',
    buildStyle: 'morph',
    strengths: ['Economy scaling', 'Unit mobility', 'Swarm tactics'],
    playstyle: 'Aggressive expansion with overwhelming numbers',
  },
}

// Unit definitions with enhanced stats
export const UNITS: Record<string, UnitStats> = {
  // ═══════════════════════════════════════════════════════════════
  // TERRAN UNITS
  // ═══════════════════════════════════════════════════════════════
  scv: {
    id: 'scv',
    faction: 'terran',
    hp: 45,
    armor: 0,
    damage: 5,
    attackSpeed: 1500,
    range: 16,
    speed: 2.8,
    size: 11,
    vision: 256,
    cost: { minerals: 50, gas: 0 },
    buildTime: 12,
    supply: 1,
    canHarvest: true,
    canBuild: true,
    canRepair: true,
    icon: 'SCV',
    hotkey: 'S',
    producer: 'commandcenter',
  },
  marine: {
    id: 'marine',
    faction: 'terran',
    hp: 45,
    armor: 0,
    damage: 6,
    attackSpeed: 860,
    range: 160,
    speed: 2.25,
    size: 11,
    vision: 288,
    cost: { minerals: 50, gas: 0 },
    buildTime: 18,
    supply: 1,
    projectile: 'bullet',
    abilities: ['stim'],
    icon: 'MAR',
    hotkey: 'A',
    producer: 'barracks',
  },
  marauder: {
    id: 'marauder',
    faction: 'terran',
    hp: 125,
    armor: 1,
    damage: 10,
    damageBonus: { type: 'armored', amount: 10 },
    attackSpeed: 1500,
    range: 192,
    speed: 2.25,
    size: 14,
    vision: 320,
    cost: { minerals: 100, gas: 25 },
    buildTime: 21,
    supply: 2,
    projectile: 'grenade',
    abilities: ['stim'],
    icon: 'MAU',
    hotkey: 'D',
    producer: 'barracks',
  },
  reaper: {
    id: 'reaper',
    faction: 'terran',
    hp: 60,
    armor: 0,
    damage: 4,
    hits: 2,
    attackSpeed: 1100,
    range: 160,
    speed: 4.0,
    size: 11,
    vision: 288,
    cost: { minerals: 50, gas: 50 },
    buildTime: 32,
    supply: 1,
    projectile: 'bullet',
    icon: 'REA',
    hotkey: 'R',
    producer: 'barracks',
  },
  hellion: {
    id: 'hellion',
    faction: 'terran',
    hp: 90,
    armor: 0,
    damage: 8,
    damageBonus: { type: 'light', amount: 6 },
    attackSpeed: 2500,
    range: 160,
    speed: 4.25,
    size: 14,
    vision: 320,
    cost: { minerals: 100, gas: 0 },
    buildTime: 21,
    supply: 2,
    projectile: 'flame',
    icon: 'HEL',
    hotkey: 'E',
    producer: 'factory',
  },
  siegetank: {
    id: 'siegetank',
    faction: 'terran',
    hp: 175,
    armor: 1,
    damage: 15,
    damageBonus: { type: 'armored', amount: 10 },
    attackSpeed: 1040,
    range: 224,
    speed: 2.25,
    size: 20,
    vision: 352,
    cost: { minerals: 150, gas: 125 },
    buildTime: 32,
    supply: 3,
    projectile: 'shell',
    abilities: ['siege'],
    icon: 'TNK',
    hotkey: 'S',
    producer: 'factory',
  },
  thor: {
    id: 'thor',
    faction: 'terran',
    hp: 400,
    armor: 2,
    damage: 30,
    attackSpeed: 1280,
    range: 224,
    speed: 1.87,
    size: 32,
    vision: 352,
    cost: { minerals: 300, gas: 200 },
    buildTime: 43,
    supply: 6,
    projectile: 'shell',
    splash: 15,
    requirements: ['armory'],
    icon: 'THR',
    hotkey: 'T',
    producer: 'factory',
  },
  medivac: {
    id: 'medivac',
    faction: 'terran',
    hp: 150,
    armor: 1,
    damage: 0,
    attackSpeed: 0,
    range: 0,
    speed: 2.75,
    size: 18,
    vision: 352,
    cost: { minerals: 100, gas: 100 },
    buildTime: 30,
    supply: 2,
    flying: true,
    icon: 'MED',
    hotkey: 'D',
    producer: 'starport',
  },
  viking: {
    id: 'viking',
    faction: 'terran',
    hp: 135,
    armor: 0,
    damage: 10,
    damageBonus: { type: 'armored', amount: 4 },
    hits: 2,
    attackSpeed: 1430,
    range: 288,
    speed: 2.75,
    size: 16,
    vision: 320,
    cost: { minerals: 150, gas: 75 },
    buildTime: 30,
    supply: 2,
    flying: true,
    projectile: 'missile',
    icon: 'VIK',
    hotkey: 'V',
    producer: 'starport',
  },

  // ═══════════════════════════════════════════════════════════════
  // PROTOSS UNITS
  // ═══════════════════════════════════════════════════════════════
  probe: {
    id: 'probe',
    faction: 'protoss',
    hp: 20,
    shield: 20,
    armor: 0,
    damage: 5,
    attackSpeed: 1500,
    range: 16,
    speed: 2.8,
    size: 11,
    vision: 256,
    cost: { minerals: 50, gas: 0 },
    buildTime: 12,
    supply: 1,
    canHarvest: true,
    canBuild: true,
    icon: 'PRB',
    hotkey: 'E',
    producer: 'nexus',
  },
  zealot: {
    id: 'zealot',
    faction: 'protoss',
    hp: 100,
    shield: 50,
    armor: 1,
    damage: 8,
    hits: 2,
    attackSpeed: 1200,
    range: 16,
    speed: 2.75,
    size: 14,
    vision: 288,
    cost: { minerals: 100, gas: 0 },
    buildTime: 27,
    supply: 2,
    icon: 'ZEA',
    hotkey: 'Z',
    producer: 'gateway',
  },
  stalker: {
    id: 'stalker',
    faction: 'protoss',
    hp: 80,
    shield: 80,
    armor: 1,
    damage: 13,
    damageBonus: { type: 'armored', amount: 5 },
    attackSpeed: 1440,
    range: 192,
    speed: 3.15,
    size: 14,
    vision: 320,
    cost: { minerals: 125, gas: 50 },
    buildTime: 30,
    supply: 2,
    projectile: 'particle',
    abilities: ['blink'],
    requirements: ['cybercore'],
    icon: 'STK',
    hotkey: 'S',
    producer: 'gateway',
  },
  sentry: {
    id: 'sentry',
    faction: 'protoss',
    hp: 40,
    shield: 40,
    armor: 1,
    damage: 6,
    attackSpeed: 1000,
    range: 160,
    speed: 2.75,
    size: 12,
    vision: 320,
    cost: { minerals: 50, gas: 100 },
    buildTime: 26,
    supply: 2,
    projectile: 'particle',
    requirements: ['cybercore'],
    icon: 'SEN',
    hotkey: 'E',
    producer: 'gateway',
  },
  immortal: {
    id: 'immortal',
    faction: 'protoss',
    hp: 200,
    shield: 100,
    armor: 1,
    damage: 20,
    damageBonus: { type: 'armored', amount: 30 },
    attackSpeed: 1450,
    range: 192,
    speed: 2.25,
    size: 20,
    vision: 288,
    cost: { minerals: 275, gas: 100 },
    buildTime: 39,
    supply: 4,
    projectile: 'plasma',
    icon: 'IMM',
    hotkey: 'I',
    producer: 'robo',
  },
  colossus: {
    id: 'colossus',
    faction: 'protoss',
    hp: 200,
    shield: 150,
    armor: 1,
    damage: 10,
    attackSpeed: 1650,
    range: 224,
    speed: 2.25,
    size: 28,
    vision: 320,
    cost: { minerals: 300, gas: 200 },
    buildTime: 54,
    supply: 6,
    projectile: 'beam',
    splash: 40,
    requirements: ['robobay'],
    icon: 'COL',
    hotkey: 'C',
    producer: 'robo',
  },

  // ═══════════════════════════════════════════════════════════════
  // ZERG UNITS
  // ═══════════════════════════════════════════════════════════════
  drone: {
    id: 'drone',
    faction: 'zerg',
    hp: 40,
    armor: 0,
    damage: 5,
    attackSpeed: 1500,
    range: 16,
    speed: 2.8,
    size: 11,
    vision: 256,
    cost: { minerals: 50, gas: 0 },
    buildTime: 12,
    supply: 1,
    canHarvest: true,
    canBuild: true,
    icon: 'DRN',
    hotkey: 'D',
    producer: 'hatchery',
  },
  zergling: {
    id: 'zergling',
    faction: 'zerg',
    hp: 35,
    armor: 0,
    damage: 5,
    attackSpeed: 696,
    range: 16,
    speed: 4.13,
    size: 10,
    vision: 256,
    cost: { minerals: 25, gas: 0 },
    buildTime: 17,
    supply: 0.5,
    spawnCount: 2,
    requirements: ['pool'],
    icon: 'ZLG',
    hotkey: 'Z',
    producer: 'hatchery',
  },
  roach: {
    id: 'roach',
    faction: 'zerg',
    hp: 145,
    armor: 1,
    damage: 16,
    attackSpeed: 1430,
    range: 128,
    speed: 3.0,
    size: 14,
    vision: 288,
    cost: { minerals: 75, gas: 25 },
    buildTime: 19,
    supply: 2,
    projectile: 'acid',
    requirements: ['warren'],
    icon: 'RCH',
    hotkey: 'R',
    producer: 'hatchery',
  },
  hydralisk: {
    id: 'hydralisk',
    faction: 'zerg',
    hp: 90,
    armor: 0,
    damage: 12,
    attackSpeed: 830,
    range: 160,
    speed: 3.15,
    size: 14,
    vision: 288,
    cost: { minerals: 100, gas: 50 },
    buildTime: 24,
    supply: 2,
    projectile: 'spine',
    requirements: ['den'],
    icon: 'HYD',
    hotkey: 'H',
    producer: 'hatchery',
  },
  mutalisk: {
    id: 'mutalisk',
    faction: 'zerg',
    hp: 120,
    armor: 0,
    damage: 9,
    attackSpeed: 1800,
    range: 96,
    speed: 4.0,
    size: 14,
    vision: 352,
    cost: { minerals: 100, gas: 100 },
    buildTime: 24,
    supply: 2,
    flying: true,
    projectile: 'glaive',
    requirements: ['spire'],
    icon: 'MUT',
    hotkey: 'T',
    producer: 'hatchery',
  },
  ultralisk: {
    id: 'ultralisk',
    faction: 'zerg',
    hp: 500,
    armor: 2,
    damage: 35,
    attackSpeed: 1100,
    range: 32,
    speed: 4.13,
    size: 32,
    vision: 288,
    cost: { minerals: 300, gas: 200 },
    buildTime: 39,
    supply: 6,
    splash: 20,
    requirements: ['cavern'],
    icon: 'ULT',
    hotkey: 'U',
    producer: 'hatchery',
  },
  queen: {
    id: 'queen',
    faction: 'zerg',
    hp: 175,
    armor: 1,
    damage: 9,
    attackSpeed: 1100,
    range: 160,
    speed: 1.3,
    size: 16,
    vision: 288,
    cost: { minerals: 150, gas: 0 },
    buildTime: 36,
    supply: 2,
    projectile: 'acid',
    icon: 'QUE',
    hotkey: 'Q',
    producer: 'hatchery',
  },
  overlord: {
    id: 'overlord',
    faction: 'zerg',
    hp: 200,
    armor: 0,
    damage: 0,
    attackSpeed: 0,
    range: 0,
    speed: 0.82,
    size: 24,
    vision: 352,
    cost: { minerals: 100, gas: 0 },
    buildTime: 18,
    supply: 0,
    flying: true,
    icon: 'OVL',
    hotkey: 'V',
    producer: 'hatchery',
  },
}

// Building definitions
export const BUILDINGS: Record<string, BuildingStats> = {
  // ═══════════════════════════════════════════════════════════════
  // TERRAN BUILDINGS
  // ═══════════════════════════════════════════════════════════════
  commandcenter: {
    id: 'commandcenter',
    faction: 'terran',
    hp: 1500,
    armor: 1,
    size: 50,
    vision: 352,
    cost: { minerals: 400, gas: 0 },
    buildTime: 71,
    supplyProvided: 15,
    produces: ['scv'],
    isBase: true,
    icon: 'CC',
    hotkey: 'C',
  },
  supplydepot: {
    id: 'supplydepot',
    faction: 'terran',
    hp: 400,
    armor: 1,
    size: 20,
    vision: 288,
    cost: { minerals: 100, gas: 0 },
    buildTime: 21,
    supplyProvided: 8,
    icon: 'SD',
    hotkey: 'S',
  },
  barracks: {
    id: 'barracks',
    faction: 'terran',
    hp: 1000,
    armor: 1,
    size: 36,
    vision: 288,
    cost: { minerals: 150, gas: 0 },
    buildTime: 46,
    produces: ['marine', 'marauder', 'reaper'],
    requirements: ['supplydepot'],
    icon: 'BRK',
    hotkey: 'B',
  },
  engineeringbay: {
    id: 'engineeringbay',
    faction: 'terran',
    hp: 850,
    armor: 1,
    size: 28,
    vision: 288,
    cost: { minerals: 125, gas: 0 },
    buildTime: 25,
    icon: 'EB',
    hotkey: 'E',
  },
  factory: {
    id: 'factory',
    faction: 'terran',
    hp: 1250,
    armor: 1,
    size: 36,
    vision: 288,
    cost: { minerals: 150, gas: 100 },
    buildTime: 43,
    produces: ['hellion', 'siegetank', 'thor'],
    requirements: ['barracks'],
    icon: 'FAC',
    hotkey: 'F',
  },
  armory: {
    id: 'armory',
    faction: 'terran',
    hp: 750,
    armor: 1,
    size: 28,
    vision: 288,
    cost: { minerals: 150, gas: 100 },
    buildTime: 46,
    requirements: ['factory'],
    icon: 'ARM',
    hotkey: 'A',
  },
  starport: {
    id: 'starport',
    faction: 'terran',
    hp: 1300,
    armor: 1,
    size: 36,
    vision: 288,
    cost: { minerals: 150, gas: 100 },
    buildTime: 36,
    produces: ['medivac', 'viking'],
    requirements: ['factory'],
    icon: 'STP',
    hotkey: 'S',
  },
  refinery: {
    id: 'refinery',
    faction: 'terran',
    hp: 500,
    armor: 1,
    size: 24,
    vision: 288,
    cost: { minerals: 75, gas: 0 },
    buildTime: 21,
    onGeyser: true,
    icon: 'REF',
    hotkey: 'R',
  },

  // ═══════════════════════════════════════════════════════════════
  // PROTOSS BUILDINGS
  // ═══════════════════════════════════════════════════════════════
  nexus: {
    id: 'nexus',
    faction: 'protoss',
    hp: 1000,
    shield: 1000,
    armor: 1,
    size: 45,
    vision: 352,
    cost: { minerals: 400, gas: 0 },
    buildTime: 71,
    supplyProvided: 15,
    produces: ['probe'],
    isBase: true,
    icon: 'NX',
    hotkey: 'N',
  },
  pylon: {
    id: 'pylon',
    faction: 'protoss',
    hp: 200,
    shield: 200,
    armor: 0,
    size: 20,
    vision: 288,
    cost: { minerals: 100, gas: 0 },
    buildTime: 18,
    supplyProvided: 8,
    powerRadius: 208,
    icon: 'PYL',
    hotkey: 'E',
  },
  gateway: {
    id: 'gateway',
    faction: 'protoss',
    hp: 500,
    shield: 500,
    armor: 1,
    size: 32,
    vision: 288,
    cost: { minerals: 150, gas: 0 },
    buildTime: 46,
    produces: ['zealot', 'stalker', 'sentry'],
    needsPower: true,
    icon: 'GW',
    hotkey: 'G',
  },
  cybercore: {
    id: 'cybercore',
    faction: 'protoss',
    hp: 550,
    shield: 550,
    armor: 1,
    size: 26,
    vision: 288,
    cost: { minerals: 150, gas: 0 },
    buildTime: 36,
    requirements: ['gateway'],
    needsPower: true,
    icon: 'CYB',
    hotkey: 'Y',
  },
  forge: {
    id: 'forge',
    faction: 'protoss',
    hp: 400,
    shield: 400,
    armor: 1,
    size: 26,
    vision: 288,
    cost: { minerals: 150, gas: 0 },
    buildTime: 32,
    needsPower: true,
    icon: 'FRG',
    hotkey: 'F',
  },
  robo: {
    id: 'robo',
    faction: 'protoss',
    hp: 450,
    shield: 450,
    armor: 1,
    size: 32,
    vision: 288,
    cost: { minerals: 200, gas: 100 },
    buildTime: 46,
    produces: ['immortal', 'colossus'],
    requirements: ['cybercore'],
    needsPower: true,
    icon: 'ROB',
    hotkey: 'R',
  },
  robobay: {
    id: 'robobay',
    faction: 'protoss',
    hp: 500,
    shield: 500,
    armor: 1,
    size: 28,
    vision: 288,
    cost: { minerals: 200, gas: 200 },
    buildTime: 46,
    requirements: ['robo'],
    needsPower: true,
    icon: 'RBY',
    hotkey: 'B',
  },
  stargate: {
    id: 'stargate',
    faction: 'protoss',
    hp: 500,
    shield: 500,
    armor: 1,
    size: 32,
    vision: 288,
    cost: { minerals: 150, gas: 150 },
    buildTime: 43,
    requirements: ['cybercore'],
    needsPower: true,
    icon: 'STG',
    hotkey: 'S',
  },
  assimilator: {
    id: 'assimilator',
    faction: 'protoss',
    hp: 450,
    shield: 450,
    armor: 1,
    size: 24,
    vision: 288,
    cost: { minerals: 75, gas: 0 },
    buildTime: 21,
    onGeyser: true,
    icon: 'ASM',
    hotkey: 'A',
  },

  // ═══════════════════════════════════════════════════════════════
  // ZERG BUILDINGS
  // ═══════════════════════════════════════════════════════════════
  hatchery: {
    id: 'hatchery',
    faction: 'zerg',
    hp: 1500,
    armor: 1,
    size: 50,
    vision: 352,
    cost: { minerals: 300, gas: 0 },
    buildTime: 71,
    supplyProvided: 6,
    produces: ['drone', 'zergling', 'roach', 'hydralisk', 'mutalisk', 'ultralisk', 'queen', 'overlord'],
    isBase: true,
    icon: 'HTH',
    hotkey: 'H',
  },
  pool: {
    id: 'pool',
    faction: 'zerg',
    hp: 1000,
    armor: 1,
    size: 32,
    vision: 288,
    cost: { minerals: 200, gas: 0 },
    buildTime: 46,
    icon: 'SPL',
    hotkey: 'S',
  },
  warren: {
    id: 'warren',
    faction: 'zerg',
    hp: 850,
    armor: 1,
    size: 26,
    vision: 288,
    cost: { minerals: 150, gas: 0 },
    buildTime: 39,
    requirements: ['pool'],
    icon: 'RWR',
    hotkey: 'R',
  },
  den: {
    id: 'den',
    faction: 'zerg',
    hp: 850,
    armor: 1,
    size: 28,
    vision: 288,
    cost: { minerals: 100, gas: 100 },
    buildTime: 29,
    requirements: ['pool'],
    icon: 'HDN',
    hotkey: 'H',
  },
  spire: {
    id: 'spire',
    faction: 'zerg',
    hp: 850,
    armor: 1,
    size: 32,
    vision: 288,
    cost: { minerals: 200, gas: 200 },
    buildTime: 71,
    requirements: ['pool'],
    icon: 'SPR',
    hotkey: 'S',
  },
  cavern: {
    id: 'cavern',
    faction: 'zerg',
    hp: 850,
    armor: 1,
    size: 36,
    vision: 288,
    cost: { minerals: 150, gas: 200 },
    buildTime: 46,
    requirements: ['pool'],
    icon: 'UCV',
    hotkey: 'U',
  },
  extractor: {
    id: 'extractor',
    faction: 'zerg',
    hp: 500,
    armor: 1,
    size: 24,
    vision: 288,
    cost: { minerals: 25, gas: 0 },
    buildTime: 21,
    onGeyser: true,
    consumesWorker: true,
    icon: 'EXT',
    hotkey: 'E',
  },
}

// Ability definitions
export const ABILITIES: Record<string, Ability> = {
  blink: {
    id: 'blink',
    name: 'Blink',
    hotkey: 'B',
    cooldown: 7000,
    range: 256,
    targetType: 'ground',
    description: 'Teleport to target location',
  },
  stim: {
    id: 'stim',
    name: 'Stimpack',
    hotkey: 'T',
    cooldown: 0,
    hpCost: 10,
    duration: 11000,
    targetType: 'self',
    description: '+50% attack and movement speed',
    effect: {
      speedBonus: 1.5,
      attackBonus: 1.5,
    },
  },
  siege: {
    id: 'siege',
    name: 'Siege Mode',
    hotkey: 'E',
    cooldown: 2000,
    targetType: 'self',
    description: 'Transform into immobile siege mode with increased range and damage',
  },
}

// Helper functions
export function getFactionUnits(factionId: FactionId): UnitStats[] {
  return Object.values(UNITS).filter(u => u.faction === factionId)
}

export function getFactionBuildings(factionId: FactionId): BuildingStats[] {
  return Object.values(BUILDINGS).filter(b => b.faction === factionId)
}

export function getUnitByHotkey(factionId: FactionId, hotkey: string): UnitStats | undefined {
  return Object.values(UNITS).find(u => u.faction === factionId && u.hotkey.toLowerCase() === hotkey.toLowerCase())
}

export function getBuildingByHotkey(factionId: FactionId, hotkey: string): BuildingStats | undefined {
  return Object.values(BUILDINGS).find(b => b.faction === factionId && b.hotkey.toLowerCase() === hotkey.toLowerCase())
}
